# build-docker:
#   stage: build

#   script:
#     - export DOCKER_PASSWORD=$(echo "$DOCKER_PASSWORD_ENCODED" | base64 --decode)
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker build -t $DOCKER_USERNAME/pactify:latest .
#     - docker push $DOCKER_USERNAME/pactify:latest

#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'

build-docker:
  image: docker:latest
  stage: build

  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""

  script:
    - export DOCKER_PASSWORD=$(echo "$DOCKER_PASSWORD_ENCODED" | base64 --decode)
    - echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/pactify:latest .
    - docker push $DOCKER_USERNAME/pactify:latest

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'