# build-docker:
#   stage: build

#   script:
#     - export DOCKER_PASSWORD=$(echo "$DOCKER_PASSWORD_ENCODED" | base64 --decode)
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker build -t $DOCKER_USERNAME/pactify:latest .
#     - docker push $DOCKER_USERNAME/pactify:latest

#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'

build-docker:
  image: docker:19.03.12
  stage: build

  services:
    - docker:19.03.12-dind

  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - apk update && apk add docker

  script:
    - export DOCKER_PASSWORD=$(echo "$DOCKER_PASSWORD_ENCODED" | base64 --decode)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/pactify:latest .
    - docker push $DOCKER_USERNAME/pactify:latest

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'